### ISSUE TITLE
text for the page

### ISSUE THREAD

**Issue by YourmotherplayscardgamesinHell** [komcrad/TheAnsonManCan#5]
Okay, so this is going to be on the about me. Lets just use 2 tabs, one for the comparisons and the fun stuff and the about me tab for the bio/contact info.

```
   "Hey everyone! So if you haven't noticed, i'll be running for freshman class president.  I'm a freshman nursing student and am very excited for the year to come! 
```

Here's a little bit about myself...
     I grew up in a Christian home and attended a private Christian school for all 12 years of my education.   I was saved at six years old through my teachers and my parents and have continued to grow in Christ since then. 
     I have two brothers, one of which is attending Cedarville this year and is a senior. My other brother is pretty tech-savvy and is pursuing a career in that. I have a fantastic group of friends, who banded together and helped immensely with my campaigning!
     Last year as a senior in high school, I was able to an EMT course as well as a few other classes at a local community college. I really have a desire to help people and thought that working as an EMT would be a great avenue to do that. After becoming nationally certified, I applied and interviewed to become a part of CUEMS for the freshman year and was accepted! So whenever you call '911' on campus, I could be the one who comes and helps you out! 
     I also have a love for music. I have been singing since as far back as I can remember. I am a member of the Men's Glee Club at Cedarville this year and am looking forward to how that goes! I also started taking piano lessons when I was 5 years old and have continued to take them ever since. I took 2 years of guitar lessons when I was younger but have since focused on piano. There was also a brief time when I played the drums, but immediately realized that it wasn't for me! (the multitasking is real)

```
 I'm running for freshman class president to make the first year at Cedarville the best it can possibly be! I have some great ideas for some events and am very excited to share them with you guys! I love comments and suggestions, so if you have any ideas for anything, feel free to send me an email! Together we're going to make this year AMAZING!
```

Here's my social media and contact info:
_in smaller font than above_
Join my FB group - "Stephen Anson for Freshman Class President"  
Follow me on Twitter: @stephenanson
Follow me on Instagram: @stephenanson97
Email -Stephenanson@cedarville.edu

---

Okay, now this is gonna go on my home page. I like the picture at the top, so this will go underneath it.

"Here are some reasons why you should vote Stephen Anson for President"

_image of Kim Jong Un next to image of me_ 
Kim Jong Un     |       Stephen Anson 
-is a communist        -is not a communist
-has millions of dedicated followers    -has 14 followers on Twitter
-is a tyrannical dictator             -never been a dictator
-has a mansion              -has a super cool website
-doesn't need to campaign to become elected            -campaigns like a mad man

_image of Prince Hans from Frozen_
Prince Hans of the Southern Isles      |      Stephen Anson of Illinois
-wants the crown at all costs                -wants freshman class presidency 
- let Anna freeze                                   - hasn't frozen anyone
- is a jerk face who totally should have been the awesome guy that everyone loved but instead turned to greed and deceit to steal the kingdom from Anna by trying to seduce her and then let her freeze to death in an icy cold wasteland filled with ice and stuff
                                                              - i have not done that

-is a bad guy                                         -isnt a bad guy
## -sings really well                                   - jealous of how good he sings

_image of Sauron_
The Dark Lord Sauron      |       Stephen Anson (baby picture that you like)

-is a dark lord                                                       -is not a dark lord
-created the one ring to enslave middle earth          - has a replica of said one ring 
-is extremely cool looking                                      -not nearly as cool looking as Sauron
-had his finger chopped off                                   -has not had his finger chopped off
- his soul turned into a giant eye after death to continue his evil work        -has not turned into an evil eye
  -has millions of Orks, Uruks, Goblins, Fell Beasts, and bad guys to do his bidding  
                                                                                            -has 74 followers on instagram =D

---

*picture of Voldemort

Voldemort                |             Stephen Anson
-Doesnt have a nose             -has a nose
- has magical powers           - can summon the strength to wake up at 7am for an 8am class
  -tries to steal the magic from Potterland?          -Doesn't do that  
  -Has seen Harry Potter                       -Has not seen any of the Harry Potter movies

---

_Picture of Michael Scott_

Michael Scott           |           Stephen Anson
-regional manager of a paper company branch                   -is not a manager of a paper company branch
-has an assistant to the regional manager                        - does not have that
- has great morale-boosting ideas                                   - has great morale-boosting ideas 
  -has an alter ego-----"Michael Skarn"                                -I don't have that
  -has a ton of killer suits                                                     -Owns one suit
  -almost jumped off the top of a building onto a bouncy castle -hasn't done that (sadly that sounds like fun)

_that would be all of them that I want to do, now i just need something that convinces them to push the "about me" tab. maybe something like this_

"If you would want to find out who this "Stephen Anson" guy is, click the "about me" tab!"

Thats all for now, ill email you pictures i want to use

**Comment by YourmotherplayscardgamesinHell** [comment]
don't know why it formatted it so weird but ok

**Comment by YourmotherplayscardgamesinHell** [comment]
correction for the frozen part, "let anna freeze and tried to kill elsa" instead of "let anna freeze"

**Comment by komcrad** [comment]
Done
