### ISSUE TITLE
Okay the final draft 

### ISSUE THREAD

**Issue by YourmotherplayscardgamesinHell** [komcrad/TheAnsonManCan#6]
The opening I think should be simple. 

---Welcome and thanks for visiting my website! Vote Stephen Anson for Freshman Class President!

I grew up in a Christian home and attended a private Christian school from kindergarten through high school. When I was six years old I accepted Christ with the help and encouragement of my teachers and parents and have continued to grow in Christ since then. I have two brothers, one of which is attending Cedarville this year as a senior. I also have a fantastic group of friends, who banded together and helped immensely with campaigning.

Last year I was able to take an Emergency Medical Technician course and a few other classes at a community college. I have always had a strong desire to help people and thought that working as an EMT would be a great avenue to do that. This semester I joined Cedarville University's Emergency Medical Services, so if you ever call '911' on campus, I could be the one to show up! I also have a great love for music. Beginning at five years old I have taken piano, guitar and voice lessons. I am a member of the Men's Glee Club at Cedarville this year and am looking forward to practicing and performing!  

That's enough about me, let's talk about us! The reason I'm running for freshman class president to make our first year at Cedarville the best it can possibly be! We've all come to a fantastic school where we have the opportunity to grow in knowledge as well as in Christ. I have great plans in store for our freshman year and can't wait to share them with you guys! I love comments and suggestions, so if you have any ideas for anything, feel free to send me an email! Together we're going to make this year AMAZING!

**Comment by YourmotherplayscardgamesinHell** [comment]
Also, David thinks that maybe instead of "Anson" it should be "Stephen" for the pictures. If it takes any more than like 3 minutes don't worry about it though.

**Comment by YourmotherplayscardgamesinHell** [comment]
Also, the main page when you first enter the url is apparently the info and not the home page. idk if we can change that

**Comment by komcrad** [comment]
I know why its doing that... either I can remove the cookie stuff completely or I can switch the logic so that Home will be the first one the load
